export const INITIAL_DATA = [
  "TOOB TOKEN? IT'S LIKE YOUR FAVORITE MEME DOG GOT A CRYPTO MAKEOVER. PICTURE MEMES MEETS CRYPTO—PURE CHAOS, PURE FUN. STRAP IN, LET'S MEME TO THE MOON!",
  "SIMPLE AND COMPLICATED MISSION: ONBOARDING THE MASSES TO ARBITRUM IN AN EASY AND VERY TOOB WAY. FOCUSING ON NON CRYPTO USERS (NORMIES).",
  "TOOB's Total supply is 10,000,000,000",
  "TOOB's LIQUIDITY: BURNED",
  "TOOB has NO PRESALE, NO TAXES, NO CONTRACT OWNERSHIP",
  "TOOB token is on Arbitrum",
  "TOOB DEVS ARE DEVELOPING CREDIT CARD INTEGRATION FOR EASIER ONBOARDING, FOR NOW YOU CAN BUY TOOB ON UNISWAP.",
  "TOOB CONTRACT ADDRESS: 0x676F7ED2D4829460f73468b36Be49e0D6505107F",
  "TOOB IT: BECAUSE EVERYTHING LOOKS BETTER WITH TOOB'S FACE ON IT! UPLOAD YOUR PIC, AND LET'S GIVE IT THE TOOB TREATMENT! GET READY TO SMILE LIKE NEVER BEFORE!",
  "Have fun with our TOOB-GPT.AI Bot. Type anything you desire and let Toob unfold the magic of AI.",
  "Wallets Like MetaMask, CoinBase And Trust Wallet Support Toob.",
  "To Send Toob To Friends, You Can Use Compatible Wallets And Send Them Directly To Their Address.",
  "Currently You Can Buy Toob On Uniswap.",
  "Toob is a real dog",
  "Toob is 10 Years Old",
  "Join the Toob community and start your crypto journey by meme-inspired fun and decentralized finance innovation. Explore Toob It, our AI-powered image transformation tool and make your own toob memes. Together, let's embark on a journey of creativity and laughter. To the moon with Toob.",
  "TOOB email: the@toob.dog",
  "TOOB telegram: https://t.me/tooobdog",
  "TOOB X: https://x.com/thetoobdog?s=21&t=QYd3sdnmj6S0oEl_tQzGqg",
  "TOOB Tiktok: https://www.tiktok.com/@the.toob.dog?_t=8lxQUIUnVvb&_r=1",
  "TOOB Sanko.tv: https://sanko.tv/thetoobdog",
]
